server:
  port: 9090
  servlet:
    context-path: /shop-manager
spring:
  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 20
      max-active: 20
      max-wait: 60000
      max-idle: 20

# freemarker
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html; charset=UTF-8
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/views/ # classpath:/templates/
    request-context-attribute: request  # request.getAttribute(requestContextAttribute)
    expose-request-attributes: true # expose request attributes to freemarker
    expose-spring-macro-helpers: true  # expose Spring macros to freemarker
    expose-session-attributes: true  # expose session attributes to freemarker
    settings:
      tag_syntax: auto_detect #html, auto_detect, simple, xml
      template_update_delay: 0 # seconds
      default_encoding: UTF-8 # UTF-8, ISO-8859-1
      output_encoding: UTF-8 # UTF-8, ISO-8859-1
      locale: zh_CN # en_US, zh_CN, zh_TW, etc.
      date_format: yyyy-MM-dd # yyyy-MM-dd, yyyy-MM-dd HH:mm:ss, etc.
      time_format: HH:mm:ss # HH:mm:ss, HH:mm, HH, etc.
      datetime_format: yyyy-MM-dd HH:mm:ss # yyyy-MM-dd HH:mm:ss, yyyy-MM-dd HH:mm, yyyy-MM-dd, etc.
      number_format: # #,###.##, #,###.##0.00, etc.
      boolean_format: true,false # true, false, yes, no, on, off, 1, 0, etc.
      template_exception_handler: html_debug # ignore, html_debug, html_verbose, throw
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.shop.manager.pojo
logging:
  level:
    com.shop.manager.mapper: DEBUG

